### DISCUSSION TITLE
Exclude mitigated / risk accepted DefectDojo findings in notification hook

### DISCUSSION THREAD

**Discussion by moxli** [secureCodeBox/secureCodeBox#2091] [Q&A] [answered]
## Your Question

I am trying to prevent a notification from being sent in case all findings are already "handled" (mitigated / false positive / risk accepted) in DefectDojo as described here: https://www.securecodebox.io/docs/hooks/notification-webhook/#configuration-of-a-notification

What rules do I need to write into my notification hook for this to work?
As far as I can tell it is only possible to configure a rule to send an email if something matches and not the other way around (If x is set don't send an email)?

I am trying it with the following rules, but I can't verify if it works due to the issue linked below.

```
    notificationChannels:
      - name: email
        type: email
        template: email
        skipNotificationOnZeroFinding: true
        rules:
        - matches:
            anyOf:
            - category: "DefectDojo Imported Finding"
              attributes:
                defectdojo.org/original-finding:
                  riskAccepted: false
            - category: "DefectDojo Imported Finding"
              attributes:
                duplicate: false
        endPoint: "Redacted"

```

Related issue: https://github.com/secureCodeBox/secureCodeBox/issues/2057

**Comment by J12934** [comment, marked as answer]
Hi @moxli 

yes as far as I understand your problem the yaml you posted would work. (if we assume #2057 is fixed)

We've used a simmilar config before for the same scenario:

```yaml
    - name: notify-for-unhandled-findings
      rules:
      - matches:
          anyOf:
          - attributes:
              defectdojo.org/original-finding: null
              duplicate: false
              falsePositive: false
              riskAccepted: false
          - attributes:
              defectdojo.org/original-finding:
                attributes:
                  falsePositive: false
                  riskAccepted: false
              duplicate: true
              falsePositive: false
              riskAccepted: false
      skipNotificationOnZeroFindings: true
      ...
```
