### ISSUE TITLE
Embedd Original (Non Duplicate) Finding in DefectDojo Hooks SyncBack Duplicate Findings

### ISSUE THREAD

**Issue by J12934** [secureCodeBox/secureCodeBox#1055]
### Is your feature request related to a problem?

The secureCodeBox allows to sync back the findings from DefectDojo via the `syncFindingsBack` mode (enabled by default). This allows to access additional information about the finding, e.g. if this finding is a duplicate to another finding in DefectDojo. In that case the findings is marked as a duplicate via the `attributes.duplicate` attribute in the secureCodeBox finding.

Unfortunately only knowing if the finding is a duplicate is often not enough, but you want to know more about the state of the "original" finding of the duplicate cluster.

- Has the risk of the finding bee marked as "acceptable" for the target
- Has the finding been identified as a false positive?

These pieces of information are currently not accessible for the "synced back" findings in the secureCodeBox as they are not included on the duplicated finding, but only on the original finding. 

### Describe the solution you'd like

I'd like the original finding to be embedded in the attributes of the duplicate secureCodeBox finding:

```yaml
{
    "id": "b1f4f0b5-1991-4635-a1b4-816303ff8c57",
    "name": "Open Port: 80/TCP",
    "location": "tcp://scanme.nmap.org:80",
    "description": "### Host\n\n**IP Address:** 45.33.32.156\n**FQDN:** scanme.nmap.org\n\n\n**Port/Protocol:** 80/tcp\n\n\n\n\n",
    "category": "DefectDojo Imported Finding",
    "severity": "INFORMATIONAL",
    "attributes": {
        "defectdojo.org/finding-id": 42,
        "defectdojo.org/finding-url": "https://defectdojo.example.com/finding/42",
        "defectdojo.org/test-id": 7,
        "falsePositive": false,
        "defectdojo.org/test-url": "https://defectdojo.example.com/test/7",
        # id of the original finding
        "defectdojo.org/original-finding-id": 6,
        # original finding (converted to scb format using sync-back mapper)
        "defectdojo.org/original-finding": {
            "id": "79e9f120-2cd3-4a1d-9d40-cb9c066eede4",
            "name": "Open Port: 80/TCP",
            "location": "tcp://scanme.nmap.org:80",
            "description": "### Host\n\n**IP Address:** 45.33.32.156\n**FQDN:** scanme.nmap.org\n\n\n**Port/Protocol:** 80/tcp\n\n\n\n\n",
            "category": "DefectDojo Imported Finding",
            "severity": "INFORMATIONAL",
            "attributes": {
                "defectdojo.org/finding-id": 6,
                "defectdojo.org/finding-url": "https://defectdojo.example.com/finding/6",
                "defectdojo.org/test-id": 5,
                "falsePositive": false,
                "defectdojo.org/test-url": "https://defectdojo.example.com/test/5",
                # original finding would be empty in the original finding
                "defectdojo.org/original-finding-id": null,
                "defectdojo.org/original-finding": null,
                "duplicate": false,
                "riskAccepted": true,
                "outOfScope": false
            },
            "osi_layer": null,
            "parsed_at": "2022-03-21T18:14:37.162640Z",
            "identified_at": null
        },
        "duplicate": true,
        "riskAccepted": false,
        "outOfScope": false
    },
    "osi_layer": null,
    "parsed_at": "2022-03-21T18:14:37.162640Z",
    "identified_at": null
}
```

### Describe alternatives you've considered

1. Replace duplicate finding with the original finding. Instead of embedding the finding, we could replace the duplicate with the original finding. So that the list of findings in the secureCodeBox always only contain original findings. This would potentially cause problems as it would be obvious anymore if the finding identified acutally was a duplicate and be kind of wierd as the finding returned by the scans wasn't really identified by it but another scan before it.
2. Only overwrite fields like `attributes.falsePositive` or risk acceptance fields by the values of the original finding in the hook. This would potentially be confusing as the falsePositive and riskAcceptance fields would not match the fields of the linked finding in DefectDojo.

### Additional context

The id of the original finding is included in the finding in DefectDojo, the field is called `duplicate_finding` (already fetched by our DefectDojo Java Api client: https://github.com/secureCodeBox/defectdojo-client-java/blob/main/src/main/java/io/securecodebox/persistence/defectdojo/models/Finding.java#L94)

The riskAccepted and outOfScope fields in the synced back findings are currently not included in the synced back findings would be a great opportunity to add them here too :)
