### ISSUE TITLE
Error when using Wpscan scantype

### ISSUE THREAD

**Issue by RealAlphaMan** [secureCodeBox/secureCodeBox#1083]
Hello everyone, please help me with Wpscan scantype. I've setup wpscan and .yaml file.
But when I apply this and view the scan, its state is Errored, Error Description:   Failed to run the Scan Container, check k8s Job and its logs for more details. I checked log, it said "error: timed out waiting for the condition". Describe jobs: "BackoffLimitExceeded: Job has reached the specified backoff limit". 
Even if I added api-token parameter of Wpscan, this error also happened. I've try increased the backoffLimit but it's not better. I think the Scan Container inside pods has some issues. What happened with it?
```
apiVersion: "execution.securecodebox.io/v1"
kind: Scan
metadata:
  name: "wpscan-old-wordpress-internal"
spec:
  scanType: "wpscan"
  parameters:
    - "--url"
    - "http://old-wordpress/"
    - "-e"
    - "vp"
    - "--api-token"
     - "<MY_REGISTERED_TOKEN>"
```

Here is the logs from container Wpscans:
```
Command:
      wpscan
      -v
      -o
      /home/securecodebox/wpscan-results.json
      -f
      json
      --url
      http://old-wordpress/
      -e
      vp
      --api-token
      <MY_REGISTERED_TOKEN>
    State:          Terminated
      Reason:       Error
      Exit Code:    4 // Sometime I get 5
      Started:      Fri, 01 Apr 2022 17:35:11 +0700
      Finished:     Fri, 01 Apr 2022 17:35:13 +0700
    Last State:     Terminated
      Reason:       Error 
      Exit Code:    4 // Sometime I get 5
      Started:      Fri, 01 Apr 2022 17:35:09 +0700
      Finished:     Fri, 01 Apr 2022 17:35:11 +0700
```
