### ISSUE TITLE
Discrepancy between SCB docs and AWS S3 endpoint docs

### ISSUE THREAD

**Issue by Spritekin** [secureCodeBox/secureCodeBox#1099]
## I'm reading the docs, the code and the AWS documentation and find it confusing
The official AWS docs say for S3 service endpoints (https://docs.aws.amazon.com/general/latest/gr/s3.html) that the endpoint is marked as s3.<region>.amazonaws.com. Note the dot between s3 and the region.

However, the code at https://docs.securecodebox.io/docs/getting-started/installation/ says:
```
s3:
  enabled: true
  # update the region to match the location of your bucket
  endpoint: "s3-eu-west-1.amazonaws.com"
```
Note the dash between the s3 and the region. 

I have been looking in the docs and there is no reference to an s3-<region>.amazonaws.com. While it might work it is not an official documentation so my suggestion would be to update the SCB docs to match the AWS docs.
