### ISSUE TITLE
Add timestamp to findings which shows the Scans creation time

### ISSUE THREAD

**Issue by J12934** [secureCodeBox/secureCodeBox#1109]
### Discussed in https://github.com/secureCodeBox/secureCodeBox/discussions/1100

<div type='discussions-op-text'>

<sup>Originally posted by **ammerzon** April 11, 2022</sup>
The [finding documentation](https://www.securecodebox.io/docs/api/finding) states that the `identified_at` attribute will often not be present. This information would be quite useful, and I wonder why it is not present more?

I assume this depends on the scanner, and there is no easy way to get to that information. Wouldn't it be helpful to get an attribute `started_at` for the scan so you have a duration with the already existing `parsed_at` attribute?</div>

Easiest thing to do would probably be to just add this under the proposed `scan_created_at` attribute, but we might want to add some more structure to it and have a `scan` attribute which bundles more metadata related info about the scan?

Like:

```yaml
{
    "name": "http",
    "description": "Port 3000 is open using tcp protocol.",
    ...
    "severity": "INFORMATIONAL",
    // new field
    "scan": {
      "created_at": "2021-06-22T12:26:54.378Z",
      "name": "foobar",
      "namespace": "default",
      "scan_type": "nmap"
    },
    "attributes": {
        "port": 3000,
        ...
    }
}
```
