### ISSUE TITLE
Got error when create new scantype Grype: failed to create containerd task: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "grype": executable file not found in $PATH: unknown

### ISSUE THREAD

**Issue by RealAlphaMan** [secureCodeBox/secureCodeBox#1116]
## I got error when create new scantype Grype base on template
Hello everyone, I've created a new scantype Grype for my scb. But I got error `failed to create containerd task: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "grype": executable file not found in $PATH: unknown`

**scannner/Dockerfile:**
```
FROM alpine:latest AS build

RUN apk --no-cache add ca-certificates

FROM scratch
COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt

RUN addgroup --system --gid 1001 grype && adduser grype --system --uid 1001 --ingroup grype
USER 1001
CMD [grype]
```

**templates/grype-scan-type.yaml:**
```
apiVersion: "execution.securecodebox.io/v1"
kind: ScanType
metadata:
  name: "grype{{ .Values.scanner.nameAppend | default ""}}"
spec:
  extractResults:
    type: grype-json
    location: "/home/securecodebox/grype-results.json"
  jobTemplate:
    spec:
      {{- if .Values.scanner.ttlSecondsAfterFinished }}
      ttlSecondsAfterFinished: {{ .Values.scanner.ttlSecondsAfterFinished }}
      {{- end }}
      backoffLimit: {{ .Values.scanner.backoffLimit }}
      {{- if .Values.scanner.activeDeadlineSeconds }}
      activeDeadlineSeconds: {{ .Values.scanner.activeDeadlineSeconds }}
      {{- end }}

      template:
        spec:
          restartPolicy: OnFailure
          affinity:
            {{- toYaml .Values.scanner.affinity | nindent 12 }}
          tolerations: 
            {{- toYaml .Values.scanner.tolerations | nindent 12 }}
          containers:
            - name: grype
              image: "{{ .Values.scanner.image.repository }}:{{ .Values.scanner.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.scanner.image.pullPolicy }}
              command:
                - "grype"
                - "-o"
                - "json"
              resources:
                {{- toYaml .Values.scanner.resources | nindent 16 }}
              securityContext:
                {{- toYaml .Values.scanner.securityContext | nindent 16 }}
              env:
                {{- toYaml .Values.scanner.env | nindent 16 }}
              volumeMounts:
                {{- toYaml .Values.scanner.extraVolumeMounts | nindent 16 }}
            {{- if .Values.scanner.extraContainers }}
            {{- toYaml .Values.scanner.extraContainers | nindent 12 }}
            {{- end }}
          volumes:
            {{- toYaml .Values.scanner.extraVolumes | nindent 12 }}
```

**Chart.yaml:**
```
apiVersion: v2
name: grype
description: A Helm chart for the grype security Scanner that integrates with the secureCodeBox.

type: application
# version - gets automatically set to the secureCodeBox release version when the helm charts gets published
version: v3.1.0-alpha1
appVersion: "latest" # Set appVersion
kubeVersion: ">=v1.11.0-0"

keywords:
  - security
  - grype
  - scanner
  - secureCodeBox
home: https://docs.securecodebox.io/docs/scanners/Grype
icon: https://docs.securecodebox.io/img/integrationIcons/Grype.svg # Upload new icon
sources:
  - https://github.com/secureCodeBox/secureCodeBox
maintainers:
  - name: name
    email: email@gmail.com
```

**values.yaml:**
```
parser:
  image:
    repository: docker.io/anchore/parser-grype
    tag: null
    pullPolicy: IfNotPresent

  ttlSecondsAfterFinished: null
  env: []

  scopeLimiterAliases: {}

  affinity: {}

  tolerations: []

scanner:
  image:
    repository: docker.io/anchore/grype
    tag: null
    pullPolicy: IfNotPresent

  nameAppend: null

  ttlSecondsAfterFinished: null
  activeDeadlineSeconds: null
  backoffLimit: 3

  resources: {}
  env: []

  extraVolumes: []

  extraVolumeMounts: []

  extraContainers: []

  securityContext:
    runAsUser: 1001
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    privileged: false
    capabilities:
      drop:
        - all

  affinity: {}

  tolerations: []

cascadingRules:
  enabled: true
```

And then I try to run a scan, the describe of pod:
```
Normal   Scheduled  17s                default-scheduler  Successfully assigned default/scan-grype-spring4shell-tomcat-wxm2n--1-jflgb to pool-bjz6t88zx-c8scj
  Normal   Pulled     16s                kubelet            Container image "docker.io/securecodebox/lurker:3.9.1" already present on machine
  Normal   Created    16s                kubelet            Created container lurker
  Normal   Started    16s                kubelet            Started container lurker
  Warning  BackOff    14s (x2 over 15s)  kubelet            Back-off restarting failed container
  Normal   Created    0s (x3 over 16s)   kubelet            Created container grype
  Warning  Failed     0s (x3 over 16s)   kubelet            Error: failed to create containerd task: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "grype": executable file not found in $PATH: unknown
  Normal   Pulled     0s (x3 over 16s)   kubelet            Container image "anchore/grype:latest" already present on machine

```

All of other files are kept original. What was wrong here? Thank you
