### ISSUE TITLE
New Trello hook (or add-on to the notification hook)

### ISSUE THREAD

**Issue by Spritekin** [secureCodeBox/secureCodeBox#1148]
## ⚓️ New Hook implementation request

A Trello hook would be an interesting feature. The hook would use the same filtering rules and on each matching rule it would create a Trello card in an specified column using a title and description based on the finding entry. This way the development teams would take the card as a development item so it is integrated in their development cycle.
Alternatively, this could work as an addon to the current notification hook with a new type.

### Is your feature request related to a problem

Yes. As described above, I would like that the findings are notified to the development teams as tickets they can take and solve.

### Describe the solution you'd like

I would like a hook that accepts the following envs in the values.yaml . This is an adjusted example using the current notification hook values.yaml example from the docs.
```
notificationChannels:
  - name: nmapopenports
    type: trello
    skipNotificationOnZeroFinding: true
    rules:
      - matches:
          anyOf:
            - category: "Open Port"
    endPoint: TRELLO_CARDS_ENDPOINT
env:
    - name: TRELLO_CARDS_ENDPOINT
      value: https://api.trello.com/1/cards   << This is a default Trello cards API endpoint, no need to change it.
    - name: TRELLO_KEY
      valueFrom:
        secretKeyRef:
          name: mytrellosecret
          key: trellokey                << This secret entry holds your unique trello API key
    - name: TRELLO_TOKEN
      valueFrom:
        secretKeyRef:
          name: mytrellosecret
          key: trellotoken            << This secret entry holds your unique trello API token
    - name: TRELLO_LIST
      value: 123a456b789c013d    << In which list ID to place the card (required)
    - name: TRELLO_LABELS
      value: "111a111b222c333f,555a666b777c888d"    << Label IDs for the card
    - name: TRELLO_POS
      value: top    << In which place in the list to put the card

```

Internally the hook would call the Trello cards API located at https://api.trello.com/1/cards. This is an standard URL and could be a default value. We pass some parameters to this endpoint to create the card.
Something like this:
```

for each finding that matches filter:
  CARD_TITLE = finding.severity + ":" + finding.name 
  CARD_DESC = finding.message
  data = {
      "key": "TRELLO_KEY",
      "token": "TRELLO_TOKEN",
      "idList": "TRELLO_LIST",
      "name": "CARD_TITLE",
      "desc": "CARD_DESC",
      "pos": "TRELLO_POS",
      "idLabels": "TRELLO_LABELS"
  }
  axios.post(endPoint, data)
```

### Describe alternatives you've considered

Tried other hooks (notification, generic-webhook) but they won't allow this kind of configuration

## Steps to implement a new hook
Hint: A general guide how to implement a new SCB Hook is documented [here](https://docs.securecodebox.io/docs/contributing/integrating-a-hook)

- [ ] Create a new folder with the name of the [hook here](https://github.com/secureCodeBox/secureCodeBox/tree/master/hooks)
- [ ] Add a `README.md` and give a brief overview of the scanner and its configuration options.
- [ ] Add a HelmChart and document all configuration options.
- [ ] Add (optional) a `Dockerfile` for the scanner if there is no existing one publicly available on dockerHub.io
- [ ] Use the [Hook-SDK](https://github.com/secureCodeBox/secureCodeBox/tree/master/hook-sdk) to implement a new hook (currently based on NodeJS)
- [ ] Add unit tests with at minimum 80% test coverage
- [ ] Add some example `scan.yaml` and `finding.yaml` files in the example folder
- [ ] Implement a [new integration or E2E test](https://docs.securecodebox.io/docs/contributing/integrating-a-hook/integration-tests) for the hook [here](https://github.com/secureCodeBox/secureCodeBox/tree/master/tests/integration)
