### ISSUE TITLE
Add option to configure OWASP ZAP attack mode

### ISSUE THREAD

**Issue by ammerzon** [secureCodeBox/secureCodeBox#1227]
## ➹ Add option to configure OWASP ZAP attack mode

As a security expert, I can configure the OWASP ZAP mode to `attack`, so that new nodes in scope are automatically scanned.

* [OWASP ZAP Modes](https://www.zaproxy.org/docs/desktop/start/features/modes/)
* [Issue](https://github.com/secureCodeBox/scanner-webapplication-zap/issues/15) from @rseedorff 

### Describe the solution you'd like

Add an option to the YAML file like the following one:

```yaml
zapConfiguration:
  global:
    # -- The ZAP Mode (safe, protected, standard, attack)
    mode: attack
```

According to @rseedorff OWASP ZAP already provides an API endpoint for setting the mode under `core/action/setMode`.

**Comment by Ilyesbdlala** [comment]
This functionality is already implemented in our `zap-advanced` ScanType (not `zap`). `zap-advanced` is a more configurable ScanType version of `zap`. It is done by setting the `.data.<volumepath>.global.mode` to the preferred mode in the `zap-advanced-scantype-config` ConfigMap. An example can be seen below:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: zap-advanced-scantype-config
data:
  1-zap-advanced-scantype.yaml: |-

    # Global ZAP Configurations
    global:
      # Sets the ZAP Session name
      sessionName: scb-integration-test
      # -- Updates all installed ZAP AddOns on startup if true, otherwise false.
      addonUpdate: true
      # -- Installs additional ZAP AddOns on startup, listed by their name:
      addonInstall:
        - pscanrulesBeta
        - ascanrulesBeta
        - pscanrulesAlpha
        - ascanrulesAlpha
      ######## Setting the mode here #################  
      mode: attack  
 ...
```

An example for a ConfigMap can be found [here](https://github.com/secureCodeBox/secureCodeBox/blob/bfd6c45f18e7e3c44a20778760d6f0214ed454a5/scanners/zap-advanced/integration-tests/scantype-configMap.yaml).
More info on [zap-advanced](https://www.securecodebox.io/docs/scanners/zap-advanced). Let me know if this solves the issue :)
