### ISSUE TITLE
Could not find test type 'SSLyze 3 Scan (JSON)' in DefectDojo API.

### ISSUE THREAD

**Issue by mjagyo** [secureCodeBox/secureCodeBox#1246]
Currently we are running a simple sslyze scan to and passed it to dd's hook:

```
apiVersion: "execution.securecodebox.io/v1"
kind: Scan
metadata:
  name: "sslyze-vpsie-example"
  labels:
    organization: "secureCodeBox"
spec:
  scanType: "sslyze"
  parameters:
    - "--mozilla_config=modern"
    - "vpsie.com"
```

After some time it throws an error: 
**Could not find test type 'SSLyze 3 Scan (JSON)' in DefectDojo API.**

I found out that it should be named "SSLyze Scan (JSON)" instead. As provided in the description "SSLyze Scan (JSON) - Import JSON report of SSLyze version 3 and higher.

May I know on where I can set those parameters in the given yaml file.
