### ISSUE TITLE
Empty Screenshot or 0 Bytes PNG File

### ISSUE THREAD

**Issue by mjagyo** [secureCodeBox/secureCodeBox#1250]
Hi,

May I ask for any setting or reason why we are getting an empty screenshot that was being uploaded to Minio?

Here is the yaml file:
```
apiVersion: "execution.securecodebox.io/v1"
kind: Scan
metadata:
  name: "screenshot-github-securecodebox.test.io"
spec:
  scanType: "screenshooter"
  parameters:
    - "https://github.com/secureCodeBox"
```

Here is the file that was being uploaded to the Minio:
![image](https://user-images.githubusercontent.com/13362819/175960745-55489b1e-3528-4a7d-9937-5e4a7a2aec63.png)

Also an empty findings.json (shown above)

Thank you so much.
