### ISSUE TITLE
Unable to create an advanced scan. KS8

### ISSUE THREAD

**Issue by renatosazup** [secureCodeBox/secureCodeBox#1309]
## 🐞 Bug report

Unable to create an advanced scan, always an error of "MountVolume.SetUp"

#### Job

```
# SPDX-FileCopyrightText: the secureCodeBox authors
# https://github.com/secureCodeBox/secureCodeBox/blob/main/scanners/zap-advanced/examples/secureCodeBox.io-scan/scan.yaml
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: "execution.securecodebox.io/v1"
kind: Scan
metadata:
  name: "zap-advanced-scan-securecodebox"
  labels:
    organization: "OWASP"
spec:
  scanType: "zap-advanced-scan"
  parameters:
    # target URL including the protocol
    - "-t"
    - "https://www.secureCodeBox.io"

```

#### Command 
```
kubectl describe pod scan-zap-advanced-scan-securecodebox-xxxx-xxxx -n owasp-zap-advanced
```

#### Output
```
Events:
  Type     Reason       Age                From               Message
  ----     ------       ----               ----               -------
  Normal   Scheduled    55s                default-scheduler  Successfully assigned owasp-zap-advanced/scan-zap-advanced-scan-securecodebox-qxnmw-xz6mp to ip-100-72-19-196.ec2.internal
  Warning  FailedMount  23s (x7 over 55s)  kubelet            MountVolume.SetUp failed for volume "zap-advanced-scantype-config" : configmap "zap-advanced-scantype-config" not found
```

**Comment by J12934** [comment]
Hi 👋

This is likely related to https://github.com/secureCodeBox/secureCodeBox/pull/1289

We haven’t gotten around to review and merge this yet. (A lot of people are currently on vacation 🙂 should hopefully be resolved in a bug fix release in the next couple of days)

You can workaround it by passing any configuration to the zapConfiguration helm value: See commented out helm values settings for the default: https://github.com/secureCodeBox/secureCodeBox/blob/main/scanners/zap-advanced/values.yaml#L160

**Comment by renatosazup** [comment]
Thanks @J12934 , do you know if I can run zap-advanced another way?


Example:

```
apiVersion: "execution.securecodebox.io/v1"
kind: Scan
metadata:
  name: "zap-advanced-scan-securecodebox"
  labels:
    organization: "OWASP"
spec:
  scanType: "zap-advanced-scan"
  parameters:
    # target URL including the protocol
    - "-t"
    - "https://www.secureCodeBox.io"
zapConfiguration:
    contexts:
      - name: appsec-context
        url: https://petstore.swagger.io/
        includePaths:
          - "https://petstore.swagger.io*"
        excludePaths:
          - ".*\\.js"
          - ".*\\.css"
          - ".*\\.png"
          - ".*\\.svg"
          - ".*\\.jpeg"
          - ".*\\swagger.json"
        apis:
          - name: scb-petstore-api
            context: appsec-context
            format: openapi # 'openapi', 'grapql', 'soap'
            url: https://petstore.swagger.io/v2/swagger.json
            hostOverride: https://petstore.swagger.io
        session:
          type: "cookieBasedSessionManagement"
        users:
          - name: appsec-user-1
            username: "appsec@teste.com"
            password: "teste"
            forced: true
        authentication:
          json-based:
              loginUrl: "https://petstore.swagger.io/access"
              loginRequestData: '{"username":"{%username%}","password":"{%password%}"}'
        verification:     
          isLoggedInIndicator: "bearer"
          isLoggedOutIndicator: ""

```

**Comment by renatosazup** [comment]
## 🐞 Bug report

Unable to create an advanced scan, always an error of "MountVolume.SetUp"

### Steps To Reproduce

#### Job

```
# SPDX-FileCopyrightText: the secureCodeBox authors
#
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zap-advanced-scan-config
data:
  2-zap-advanced-scan.yaml: |-
    # ZAP Contexts Configuration 
    contexts:
      - name: appsec-context
            url: https://petstore.swagger.io/
            includePaths:
              - "https://petstore.swagger.io*"
            excludePaths:
              - ".*\\.js"
              - ".*\\.css"
              - ".*\\.png"
              - ".*\\.svg"
              - ".*\\.jpeg"
              - ".*\\swagger.json"

---
apiVersion: "execution.securecodebox.io/v1"
kind: Scan
metadata:
  name: "zap-advanced-scan-securecodebox"
  labels:
    organization: "OWASP"
spec:
  scanType: "zap-advanced-scan"
  parameters:
    # target URL including the protocol
    - "-t"
    - "https://petstore.swagger.io/"
  volumeMounts:
    - name: zap-advanced-scan-config
      mountPath: /home/securecodebox/configs/2-zap-advanced-scan.yaml
      subPath: 2-zap-advanced-scan.yaml
      readOnly: true
  volumes:
    - name: zap-advanced-scan-config
      configMap:
        name: zap-advanced-scan-config

```




#### Command 
```
kubectl describe pod scan-zap-advanced-scan-securecodebox-xxxx-xxxx -n owasp-zap-advanced
```

#### Output
```
Events:
  Type     Reason       Age                From               Message
  ----     ------       ----               ----               -------
  Normal   Scheduled    55s                default-scheduler  Successfully assigned owasp-zap-advanced/scan-zap-advanced-scan-securecodebox-qxnmw-xz6mp to ip-100-72-19-196.ec2.internal
  Warning  FailedMount  23s (x7 over 55s)  kubelet            MountVolume.SetUp failed for volume "zap-advanced-scantype-config" : configmap "zap-advanced-scantype-config" not found
```
