### ISSUE TITLE
⚓️ Add NMAP Findings post processing to update the severity of port findings

### ISSUE THREAD

**Issue by rseedorff** [secureCodeBox/secureCodeBox#131]
As a secureCodeBox user i would like to be able to change / manipulate the nmap findings severity, based on a simple rule pattern. By default all NMAP Port findings are classified with the severity *Informational*. In some use cases i would like to change the port specific severity classification based on custom rules. For example if some port ranges are prohibited 🚫 to use.

The custom severity configuration should also be applied if the NMAP scan will be started by *cascadingScanRules* (e.g. as subsequent scan started by AMASS).

**Describe the solution you'd like**
In the secureCodeBox v1 there is an NMAP specific implementation example how to change some port specific severity classifications, but without any configuration options: https://github.com/secureCodeBox/engine/commit/c40b499c9947b5d3b601c5ba43427a0d781c01b4

An example configuration could look something like this:
```yaml
openport:
  port: 21
    severity: HIGH
  port: 22
    severity: MEDIUM
  port: 389
    severity: HIGH
  port: 9200
    severity: LOW
```

**Describe alternatives you've considered**
The *updatefield-hook* implements a lightweight findings post processing. But currently it is only possible to add new attributes to findings. But it has no feature to manipulate finding attributes based on rules. Extending the updatefield-hook in this way would maybe leed to a more generic solution which could also apply to other scanners and usecases.

For a more generic approach maybe the cascadingRule definition configuration semantic could be a good example how to configure the post processing:

```yaml

rules:
  - rule:
       matches:
         anyOf:
           - category: "Open Port"
              attributes:
                port: 21
                state: open
           - category: "Open Port"
              attributes:
                port: 389
                state: open
        attribute:
          name: "severity"
          value: "high"
  - rule:
       matches:
         anyOf:
           - category: "Open Port"
              attributes:
                port: 22
                state: open
        attribute:
          name: "severity"
          value: "medium"
  - rule:
       matches:
         anyOf:
           - category: "Open Port"
              attributes:
                port: 9200
                state: open
        attribute:
          name: "severity"
          value: "low"
```

**Comment by SebieF** [comment]
Would it be sufficient to add a new rule attribute to the update-field hook?

```bash
attribute:
  # attribute.name -- The name of the attribute you want to add to each finding result
  name: "severity"
  # attribute.value -- The value of the attribute you want to add to each finding result
  value: "super high"
  # possible examples:
  rule: "port != 22"
  #rule: "state == filtered"
```
And how complex should the rules possibly be? Should something like "port == 22 && service == ssh" also be supported?

**Comment by J12934** [comment]
I'd suggest the following syntax 😄:

```yaml
rules:
  - matches:
      anyOf:
        - category: "Open Port"
          attributes:
            port: 21
            state: open
        - category: "Open Port"
          attributes:
            port: 389
            state: open
    override:
      severity: "high"
      description: "Telnet is bad"
  - matches:
      anyOf:
        - category: "Open Port"
          attributes:
            port: 42
            state: open
    override:
      severity: "Informational"
      falsePositive: true
      description: "False Positive due to VPN weirdness"
```
