### ISSUE TITLE
Add securityContext for PodSecurity Configuration to all scanTypes

### ISSUE THREAD

**Issue by rseedorff** [secureCodeBox/secureCodeBox#1330]
In the scanType HelmCharts it is currently not possible to configure `PodSecurityContext` like `fsGroup` but only container specific securityContext.

All scanType Chart must be extended for that. Example:

```
scanner:
   # scanner.podSecurityContext -- Optional securityContext set on scanner pod (see: 
  https://kubernetes.io/docs/tasks/configure-pod-container/security-context/)
  podSecurityContext:
    fsGroup: 2000
  # scanner.securityContext -- Optional securityContext set on scanner container (see: 
  https://kubernetes.io/docs/tasks/configure-pod-container/security-context/)
  securityContext:
    # scanner.securityContext.runAsNonRoot -- Enforces that the scanner image is run as a non root user
    runAsNonRoot: false
    # scanner.securityContext.readOnlyRootFilesystem -- Prevents write access to the containers file system
    readOnlyRootFilesystem: false
    # scanner.securityContext.allowPrivilegeEscalation -- Ensure that users privileges cannot be escalated
    allowPrivilegeEscalation: false
    # scanner.securityContext.privileged -- Ensures that the scanner container is not run in privileged mode
    privileged: false
    capabilities:
      drop:
        # scanner.securityContext.capabilities.drop[0] -- This drops all linux privileges from the container.
        - all
```
