### ISSUE TITLE
Dashboard Importer Job in Elastic-Hook must be configurable

### ISSUE THREAD

**Issue by rseedorff** [secureCodeBox/secureCodeBox#1332]
- [ ] Ressource Quota for the Import Job must be configurable
- [ ] Dashboard Import should be configurable:

```
dashboardImporter:
  enabled: false
  image:
    # image.repository -- Image repository for the dashboard importer job
    repository: securecodebox/persistence-elastic-dashboard-importer
    # image.tag -- Image tag for the dashboard importer job
    # @default -- defaults to the charts version
    tag: null
  # dashboardImporter.resources -- CPU/memory resource requests/limits (see: https://kubernetes.io/docs/tasks/configure-pod-container/assign-memory-resource/, https://kubernetes.io/docs/tasks/configure-pod-container/assign-cpu-resource/)
  resources: {}
  #   resources:
  #     requests:
  #       memory: "256Mi"
  #       cpu: "250m"
  #     limits:
  #       memory: "512Mi"
  #       cpu: "500m"
  # dashboardImporter.securityContext -- Optional securityContext set on scanner container (see: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/)
  securityContext:
    # scanner.securityContext.runAsNonRoot -- Enforces that the scanner image is run as a non root user
    runAsNonRoot: false
    # scanner.securityContext.readOnlyRootFilesystem -- Prevents write access to the containers file system
    readOnlyRootFilesystem: false
    # scanner.securityContext.allowPrivilegeEscalation -- Ensure that users privileges cannot be escalated
    allowPrivilegeEscalation: false
    # scanner.securityContext.privileged -- Ensures that the scanner container is not run in privileged mode
    privileged: false
    capabilities:
      drop:
        # scanner.securityContext.capabilities.drop[0] -- This drops all linux privileges from the container.
        - all
```
