### ISSUE TITLE
I have a question about httpAuthSessionManagement

### ISSUE THREAD

**Issue by renatosazup** [secureCodeBox/secureCodeBox#1528]
## Your Question

I not found a example with httpAuthSessionManagement

```
authentication: 
  json-based:
    loginUrl: "http://example.com/rest/user/login"
    loginRequestData: '{"email":"admin@juice-sh.op","password":"admin123"}'
```

### Response Bearer token

`http://example.com/rest/user/login`
```
{
   "token": "..."
}
```

### Reference

https://github.com/secureCodeBox/secureCodeBox/tree/main/scanners/zap-advanced/examples
