### ISSUE TITLE
🐞 HelmChart kubeVersion field prevents installing Charts on a a pre-release K8S

### ISSUE THREAD

**Issue by rseedorff** [secureCodeBox/secureCodeBox#153]
**Describe the bug**
All SCB HelmCharts contain the kubeVersion field to ensure the K8S version meets the SCB requirements. 

### Example Operator Chart
```yaml
apiVersion: v2
name: operator
description: secureCodeBox Operator to automate the execution of security scans on kubernetes

type: application

# version - gets automatically set to the secureCodeBox release version when the helm charts gets published
version: latest
kubeVersion: ">=v1.11.0"
```

The current definition results in an error if the K8S is using a pre-release version, even if its never than the kubeVersion semversion:

```bash
helm --namespace securecodebox-system upgrade --install securecodebox-operator secureCodeBox/operator --version v2.0.0-rc.12
Error: UPGRADE FAILED: chart requires kubeVersion: >=v1.11.0 which is incompatible with Kubernetes v1.16.6-beta.0
```

**Expected behavior**
It would be great to support Kubernetes pre-release versions. As explained in the helm issue https://github.com/helm/helm/issues/3810 this could be done by adding a pre-release extension to the kube version field:

### Solution
```yaml
apiVersion: v2
name: operator
description: secureCodeBox Operator to automate the execution of security scans on kubernetes

type: application

# version - gets automatically set to the secureCodeBox release version when the helm charts gets published
version: latest
kubeVersion: ">=v1.11.0-0"
```
