### ISSUE TITLE
Nmap Findings include only one **ipv4** address

### ISSUE THREAD

**Issue by J12934** [secureCodeBox/secureCodeBox#1678]
### Describe the bug

The current state of the nmap parser only considers ipv4 address and will only include one even if nmap has identified more then one address for the host

### Steps To Reproduce

Start the following scan (cluster must be ready to handle ipv6 traffic)

```yaml
apiVersion: "execution.securecodebox.io/v1"
kind: Scan
metadata:
  name: "nmap-scanme.nmap.org"
spec:
  scanType: "nmap"
  parameters:
    - "-6" # force ipv6 mode
    - scanme.nmap.org
```

Findings won't have a ip address set.

### Expected behavior

Include all ips for a host in the finding (including v4 & v6)

### System (please complete the following information):

 - secureCodeBox Version/Release: any
