### ISSUE TITLE
semgrep scanner not working

### ISSUE THREAD

**Issue by cnsino** [secureCodeBox/secureCodeBox#1737]
### Describe the bug
use example.yml test
```
apiVersion: "execution.securecodebox.io/v1"
kind: Scan
metadata:
  name: "semgrep-vulnerable-flask-app"
spec:
  volumes:
    - name: test-dir
      emptyDir: {}
  volumeMounts:
    - mountPath: "/test/"
      name: test-dir
  scanType: "semgrep"
  parameters:
    - "-c"
    - "p/ci"
    - "/test/flask"
  initContainers:
    - name: "provision-git"
      image: bitnami/git
      command:
        - git
        - clone
        - "https://github.com/we45/Vulnerable-Flask-App"
        - /test/flask
      volumeMounts:
        - mountPath: "/test/"
          name: test-dir
```
Get Error

1. kubectl get scan

NAME                           TYPE      STATE     FINDINGS
semgrep-vulnerable-flask-app   semgrep   Errored  

2.  kubectl logs job/scan-semgrep-vulnerable-flask-app-cjvtp

Defaulted container "semgrep" out of: semgrep, lurker, provision-git (init)
METRICS: Using configs from the Registry (like --config=p/ci) reports pseudonymous rule metrics to semgrep.dev.
To disable Registry rule metrics, use "--metrics=off".
Using configs only from local files (like --config=xyz.yml) does not enable metrics.

More information: https://semgrep.dev/docs/metrics

Fetching rules from https://semgrep.dev/registry.
