### ISSUE TITLE
openapi scan using a configmap for openapi specification for ZAP advanced scan

### ISSUE THREAD

**Issue by SitoRBJ** [secureCodeBox/secureCodeBox#1772]
## Your Question

Hello everyone, a pleasure to write here and first of all I would like to say that I love the project and you guys are great!

Secondly, I would like to ask about the ZAP advanced scan option to attach the specification of openapi through a configmap. 

In the documentation, we found:

```yaml
  apis:
   . . .
      configMap:
        # Object with two keys: "name" name of the config map, and "key" which is the key / property in the configmap which holds the openapi spec file.
        name: my-configmap-with-openapi-spec
        key: openapi.yaml
```

So it seems to me that we can use a configmap to load the openapi specification.

With this in mind, I have the following configuration:

- ZAP advanced scan

```yaml
apiVersion: "execution.securecodebox.io/v1"
kind: Scan
metadata:
  name: "zap-advanced-scan-test"
  namespace: securecodebox-system
  labels:
    organization: "OWASP"
spec:
  scanType: "zap-advanced-scan"
  parameters:
    # target URL including the protocol
    - "-t"
    - "<MY_TARGET>"
    - "--context"
    - "openapi-test-context"
  volumeMounts:
    - name: zap-advanced-scan-config-test
      mountPath: /home/securecodebox/configs/2-zap-advanced-scan.yaml
      subPath: 2-zap-advanced-scan.yaml
      readOnly: true
  volumes:
    - name: zap-advanced-scan-config-test
      configMap:
        name: zap-advanced-scan-config-test
```

- ZAP advanced scan configmap

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: zap-advanced-scan-config-test
  namespace: securecodebox-system
data:
  2-zap-advanced-scan.yaml: |-

    # -- Optional general ZAP Configurations settings.
    # -- Optional list of ZAP Context definitions
    contexts:
      # -- Name to be used to refer to this context in other jobs, mandatory
      - name: openapi-test-context
        # -- The top level URL
        url: <MY_TARGET>
        # -- An optional list of regexes to include in the ZAP context
        includePaths:
          - "<MY_TARGET>/.*"
    # -- Optional list of API definitions
    apis:
      # -- Name to be used to refer to this API in other jobs, mandatory
      - name: <TARGET_NAME>
        # -- Url to start importing the API from, default: first context URL
        url: <MY_TARGET>/
        # -- The URL of the OpenAPI specification for the API
        hostOverride: <MY_TARGET>/
        # -- The format of the OpenAPI specification (either "yaml" or "json")
        format: openapi
        context: openapi-test-context
        configMap:
        # Object with two keys: "name" name of the config map, and "key" which is the key / property in the configmap which holds the openapi spec file.
          name: openapi-test-cm
          key: openapi.yaml
```

Having created the configmap with the specifications created previously with the name `openapi-test-cm`.

```bash
k -n securecodebox-system get cm
NAME                            DATA   AGE
openapi-test-cm                 1      146m
zap-advanced-scan-config-test   1      136m
```

The scan seems to be successful and I can see the following logs:

```bash
2023-06-20 13:43 ZapConfigureContext INFO    : Configuring a new ZAP Context with name: openapi-test-context
2023-06-20 13:43 ZapClient    INFO    : Configuring API Import
2023-06-20 13:43 ZapConfigureApi INFO    : Trying to start API Import with target url: '<MY_TARGET>'
2023-06-20 13:43 ZapConfigureApi INFO    : Import OpenAPI Spec from (<MY_TARGET>)
2023-06-20 13:43 ZapConfigureApi INFO    : Number of Imported URLs: 2
```

This leads me to believe that it is not importing the content of the configmap, but is looking at the scanned URL.

So, it seems obvious that I am not configuring the scan and configmaps correctly but I am not able to detect the error, could you tell me where I am failing?

Thank you in advance
