### ISSUE TITLE
🐞 Missing CRD spec for `concurrencyPolicy`

### ISSUE THREAD

**Issue by rseedorff** [secureCodeBox/secureCodeBox#2002]
### Describe the bug

The new feature #275 seems to be broken due to a missing CRD spec. 

### Steps To Reproduce
Trying to use the feature in scheduled scans results in an error:

Example `scheduledScan`:
```yaml
apiVersion: execution.securecodebox.io/v1
kind: ScheduledScan
metadata:
  name: nmap-test
spec:
  interval: 24h
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  scanSpec:
    scanType: "nmap"
    parameters:
       ...
```

Result / Error:
```sh
error validating data: ValidationError(ScheduledScan.spec): unknown field "concurrencyPolicy" in io.securecodebox.execution.v1.ScheduledScan.spec
```

### Expected behavior

No error

### System (please complete the following information):
- SCB v4.1.0
- Kubernetes 1.24
