### ISSUE TITLE
How to Pass Annotations to Pods

### ISSUE THREAD

**Issue by Alon-Katz** [secureCodeBox/secureCodeBox#2263]
Hey,

In my use case, I am utilizing Karpenter for pod scheduling and I need to ensure that the pods created through SecureCodeBox CRDs (scanner, parser and hook) have the annotation "karpenter.sh/do-not-evict" to prevent them from being evicted.

However, I could not find a way to pass this annotation to the pods. As I understand, SecureCodeBox creates a CRD which in turn creates jobs that eventually spin up the pods. Could you guide me on how I can pass annotations to these pods?

**Comment by Weltraumschaf** [comment]
Hi @Alon-Katz,

thanks for submitting this issue. We will discuss this in the team.

**Comment by J12934** [comment]
Hi, good question.

Basically podAnnotations and labels are missing as an option in all our charts. Would be great to add them.

The ScanType CRD itself already supports pod annotations&labels as the have an entire kubernetes job template in it where this can be configured.

For ParseDefinitions and Hooks this would be required to be added as new fields to the CRD's as they don't expose the full jobTemplate.

So to support your use case the following changes would be required. Happy to accept PR's for it:
- [ ] Add pod annotations and label support for ParseDefinition & Hook CRD's
- [ ] Add helm values & templates to configure pod annotations and labels on the operator chart
- [ ] Add helm values & templates to configure pod annotations for ScanTypes in all scanner charts
- [ ] Add helm values & templates to configure pod annotations for ParseDefinitions in all scanner charts
- [ ] Add helm values & templates to configure pod annotations for ScanCompletionHooks in all hook charts

**Comment by Alon-Katz** [comment]
Hi @J12934 ,  I've attempted to configure the ScanType to work with custom annotations, but it appears to be completely ignoring them. I'm deploying the following Helm file::
```
# Source: kics-scanner/templates/kics-scan-type.yaml
# SPDX-FileCopyrightText: the secureCodeBox authors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: "execution.securecodebox.io/v1"
kind: ScanType
metadata:
  name: "kics"
spec:
  extractResults:
    type: kics-json
    location: "/home/securecodebox/kics-results.sarif"
  jobTemplate:
    spec:
      suspend: false
      backoffLimit: 3

      template:
        metadata:
          annotations:
            karpenter.sh/do-not-evict: "true"
        spec:
          restartPolicy: OnFailure
          nodeSelector:
            applications: default
          affinity:
            {}
          tolerations:
            - effect: NoSchedule
              key: applications/default
              operator: Exists
          securityContext:
            {}
          containers:
            - name: kics
              image: "docker.io/checkmarx/kics:v1.7.12"
              imagePullPolicy: IfNotPresent
              command:
                - "kics"
                - "-o"
                - "/home/securecodebox/"
                - "--output-name"
                - "kics-results"
                - "--report-formats"
                - "sarif"
                - "--ignore-on-exit"
                - "results"
              resources:
                limits:
                  cpu: 500m
                  memory: 512Mi
                requests:
                  cpu: 250m
                  memory: 256Mi
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                  - all
                privileged: false
                readOnlyRootFilesystem: false
                runAsNonRoot: false
              env:
                []
              volumeMounts:
                []
          volumes:
            []
```
However, the ScanType is being deployed with an empty metadata field, which effectively removes the added annotation. Do you have any idea why this might be happening?
