### ISSUE TITLE
improve security Deployment Workload

### ISSUE THREAD

**Issue by kaz-33** [secureCodeBox/secureCodeBox#2347]
## ➹ New Feature implementation request

I run kube-score to see the workload security level deployment. I fix some issue by values file or patchs.
But still some security issue.
Could you integrate this values on the values file.?

### Is your feature request related to a problem?
```
parsrer -->
Set securityContext.runAsUser to a value > 10000   --> kyverno
Set securityContext.runAsGroup to a value > 10000  --> kyverno
Ephemeral Storage limit is not set   --> Values fnct pas...kyverno ou patch?

lurker -> 
A userid above 10 000 is recommended to avoid conflicts with thehost. Set securityContext.runAsUser to a value > 10000 
A groupid above 10 000 is recommended to avoid conflicts with the host. Set securityContext.runAsGroup to a value > 10000 
Ephemeral Storage limit is not set   Resource limits are recommended to avoid resource DDOS. Set  resources.limits.ephemeral-storage                                                                               

v1/Service controller-manager-metrics-service in securecodebox-system         💥       
    [CRITICAL] Service Targets Pod
        · The services selector does not match any pods
```

### Describe the solution you'd like
exemple:
```
lurker:
  image:
    pullPolicy: Always
    repository: docker.io/securecodebox/lurker
    tag: 4.4.1
  securityContext
   runAsUser: 10010
  runAsGroup: 10010
  resources:
     limit:
       ephemeral-storage: 100Mi
    request:
      ephemeral-storage: 100Mi
```
same for parser.
