### ISSUE TITLE
Use proxy for persistence-defectdojo 

### ISSUE THREAD

**Issue by kaz-33** [secureCodeBox/secureCodeBox#2786]
## Your Question
Hi Team, 
do you have a parameter or other way to use a proxy between persistence-defectojo and defectdojo?
Br

**Comment by kaz-33** [comment]
No idea?

**Comment by J12934** [comment]
Hi @kaz-33 

You can configure http proxies for the defectdojo hook by configuring them via env vars.
I did it in the past but don't have an example handy.

Problem with the DefectDojo hook is that its the only component in the SCB which is written is java an uses different vars then the the rest.

I think i've used this JAVA_TOOL_OPTIONS env var to then pass it the proxy settings like this:

```yaml
hook:
  env:
    - name: "JAVA_TOOL_OPTIONS"
      value: "-Dhttp.proxyHost=10.42.42.42 -Dhttp.proxyPort=8080"
```
