### ISSUE TITLE
more than one level of cascading

### ISSUE THREAD

**Issue by kaz-33** [secureCodeBox/secureCodeBox#2864]
## Your Question
Is it possible to generate more than one level of cascading?

NMAP HOST--> NMAP PORT --> SSH-AUDIT?
or only
NMAP HOST/PORT --> SSH-AUDIT

**Comment by Weltraumschaf** [comment]
Hi @kaz-33 

Yes, that's possible. See the [how-to for cascading rules](https://www.securecodebox.io/docs/how-tos/scanning-networks). 

You need to define and use appropriate `labels` and `matchLabels`.

**Comment by Weltraumschaf** [comment]
This seems dublicated by #2862.

**Comment by J12934** [comment]
See also the newly added diagram on the cascading hook doc.

https://www.securecodebox.io/docs/hooks/cascading-scans

Also pls have a look at the CascadingRule API Reference for how to configure them yourself: https://www.securecodebox.io/docs/api/crds/cascading-rule

**Comment by J12934** [comment]
I don't think the hook allow to change the label selector in later scans.

securecodebox.io/intensive and such should match the original scan otherwise they loose their meening.
if the later scans would have another scope than the original one you couldn't really control anything

can you try removing the 

```yaml
    cascades:
      inheritAffinity: true
      matchLabels:
        securecodebox.io/intensive: high
        securecodebox.io/invasive: invasive
```

section for the cascade.
