### ISSUE TITLE
Accept self signed certificates for elasticsearch backends 

### ISSUE THREAD

**Issue by rseedorff** [secureCodeBox/secureCodeBox#291]
**Is your feature request related to a problem? Please describe.**

As a secureCodeBox User i would like to use a self hosted elasticsearch backend for vulnerability analytics. Those backends may come with self signed certificates. Currently it is not possible to integrate due to the fact the elasticsearch client don't accept untrusted or self signed certificates. The elasticsearch persistence provider helm chart has no configuration option to change this behaviour.

**Describe the solution you'd like**

It should be possible to configure the elasticsearch client to accept self signed certificates.

### Example
```yaml
# authentication -- Configure authentication schema and credentials the persistence provider should use to connect to elasticsearch
# user and apikey are mutually exclusive, only set one!
authentication:
  # To turn off certificate verification set rejectUnauthorized: false, otherwise true
  rejectUnauthorized: true
  # If you want to add your own CA file mount it at `./cacert.pem` and set additionalCaFile: true, otherwise false
  additionalCaFile: false
```

The corresponding elasticsearch client configuration is implemented here:
https://github.com/secureCodeBox/secureCodeBox/blob/f29e18c145f8e377d389aa8c403cb9efcf22494a/hooks/persistence-elastic/hook.js#L35-L38

**Describe alternatives you've considered**
none

**Additional context**

I found a possible implementation solution here:
- https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/client-connecting.html#auth-ssl
- https://7thzero.com/blog/using-nodejs-to-connect-to-elasticsearch-with-a-private-certificate-authority.
