### ISSUE TITLE
Support for Custom S3 Services with a Custom Root CA

### ISSUE THREAD

**Issue by rseedorff** [secureCodeBox/secureCodeBox#297]
As secureCodeBox operations user i would like to integrate and configure custom S3 based persistence services instead of public available services like AWS Buckets, GCP Storage or DO. 

**Is your feature request related to a problem? Please describe.**

By now it is already possible to configure a custom S3 Backend as documented here: 
- https://docs.securecodebox.io/docs/getting-started/installation#using-a-hosted-s3-buckets-as-storage-backend
- https://github.com/secureCodeBox/secureCodeBox/tree/main/operator#chart-configuration

But one feature is missing in the case of custom/internal S3 Services. It must be possible to add and configure custom root CA's for all secureCodeBox Components (Operator, Scanner, Hooks,...) to ensure a valid TLS based connection, if the custom S3 Service uses non public avaliable certificates.

**Describe the solution you'd like**

Implement a configuration Option for all HelmCharts to add a custom Root CA based on a given configMap containing the CA Certificate.

SCB Components involved here:

- [x] SCB Operator: https://github.com/secureCodeBox/secureCodeBox/tree/main/operator
- [x] SCB Lurcher: https://github.com/secureCodeBox/secureCodeBox/tree/main/lurcher
- [x] All Scanner Parser ([parseDefinition](https://docs.securecodebox.io/docs/api/crds/parse-definition)):  https://github.com/secureCodeBox/secureCodeBox/tree/main/scanners ...
- [x] All Hooks ([ScanCompletionHook](https://docs.securecodebox.io/docs/api/crds/scan-completion-hook)): https://github.com/secureCodeBox/secureCodeBox/tree/main/hooks ...

## Implementation Hints:
Regarding the parseDefinition and ScanCompletionHook CRDs we have already implemented the possibility for _ENV_, _Mount_ and _FileMount_ configurations in the corresponding SCB CRD and controller. Additional informations are documented in issue #212.

What is missing here is to add this configuration option to all Scanner and Hooks HelmChart by default. The following hints will guide you through some necessary steps:

#### Existing CRD _ScanCompletionHook_ Definition
https://github.com/secureCodeBox/secureCodeBox/blob/3f22b172db08914626e5f199b78d54c93609fccf/operator/apis/execution/v1/scancompletionhook.go#L38-L65

#### Example Hook HelmChart Value Configuration:
The following code shows an example how the missing configuration option should look like (for all existing hook charts). Based on https://github.com/secureCodeBox/secureCodeBox/blob/main/hooks/declarative-subsequent-scans/values.yaml
```yaml
# example Hook configuration values
hookJob:
  # hookJob.ttlSecondsAfterFinished -- seconds after which the kubernetes job for the hook will be deleted. Requires the Kubernetes TTLAfterFinished controller: https://kubernetes.io/docs/concepts/workloads/controllers/ttlafterfinished/
  ttlSecondsAfterFinished: null
  # hookJob.env -- Optional environment variables mapped into each scanJob (see: https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/)
  env: []
  # hookJob.envFrom -- Optional mount environment variables from configMaps or secrets (see: https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/#configure-all-key-value-pairs-in-a-secret-as-container-environment-variables)
  envFrom: []
  # hookJob.extraVolumes -- Optional Volumes mapped into each hookJob (see: https://kubernetes.io/docs/concepts/storage/volumes/)
  extraVolumes:
    - name: ca-workdir
      emptyDir: {}
  # hookJob.extraVolumeMounts -- Optional VolumeMounts mapped into each hookJob (see: https://kubernetes.io/docs/concepts/storage/volumes/)
  extraVolumeMounts:
    - mountPath: /etc/ssl/
      name: ca-workdir
```

#### Example Hook HelmChart Template implementation:
based on: https://github.com/secureCodeBox/secureCodeBox/blob/main/hooks/declarative-subsequent-scans/templates/declerative-subsequent-scans-hook.yaml

```yaml
apiVersion: "execution.securecodebox.io/v1"
kind: ScanCompletionHook
metadata:
  name: {{ include "declarative-subsequent-scans.fullname" . }}
spec:
  type: ReadOnly
  image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.Version }}"
  ttlSecondsAfterFinished: {{ .Values.hookJob.ttlSecondsAfterFinished }}
  serviceAccountName: declarative-combined-scans
  env:  {{ include " .Values.hookJob.env" . }}
  volumes:  {{ include " .Values.hookJob.extraVolumes" . }}
  volumeMounts:  {{ include " .Values.hookJob.extraVolumeMounts" . }}
```

#### Existing CRD _parseType_ Definition
https://github.com/secureCodeBox/secureCodeBox/blob/3f22b172db08914626e5f199b78d54c93609fccf/operator/apis/execution/v1/parsedefinition_types.go#L27-L49

#### Example Scanner HelmChart Value Configuration:
The following code shows an example how the missing configuration option should look like (for all existing scanner charts). Based on: https://github.com/secureCodeBox/secureCodeBox/blob/main/scanners/amass/values.yaml

```yaml
# example Scanner (Parser) configuration values
parseJob:
  # parseJob.ttlSecondsAfterFinished -- seconds after which the kubernetes job for the hook will be deleted. Requires the Kubernetes TTLAfterFinished controller: https://kubernetes.io/docs/concepts/workloads/controllers/ttlafterfinished/
  ttlSecondsAfterFinished: null
  # parseJob.env -- Optional environment variables mapped into each scanJob (see: https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/)
  env: []
  # parseJob.envFrom -- Optional mount environment variables from configMaps or secrets (see: https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/#configure-all-key-value-pairs-in-a-secret-as-container-environment-variables)
  envFrom: []
  # parseJob.extraVolumes -- Optional Volumes mapped into each hookJob (see: https://kubernetes.io/docs/concepts/storage/volumes/)
  extraVolumes:
    - name: ca-workdir
      emptyDir: {}
  # parseJob.extraVolumeMounts -- Optional VolumeMounts mapped into each hookJob (see: https://kubernetes.io/docs/concepts/storage/volumes/)
  extraVolumeMounts:
    - mountPath: /etc/ssl/
      name: ca-workdir
```
#### Example Parser HelmChart Template implementation:
based on https://github.com/secureCodeBox/secureCodeBox/blob/main/scanners/amass/templates/amass-parse-definition.yaml:

```yaml
apiVersion: "execution.securecodebox.io/v1"
kind: ParseDefinition
metadata:
  name: "amass-jsonl"
spec:
  handlesResultsType: amass-jsonl
  image: "{{ .Values.parserImage.repository }}:{{ .Values.parserImage.tag | default .Chart.Version }}"
  ttlSecondsAfterFinished: {{ .Values.parseJob.ttlSecondsAfterFinished }}
  env:  {{ include " .Values.parseJob.env" . }}
  volumes:  {{ include " .Values.parseJob.extraVolumes" . }}
  volumeMounts:  {{ include " .Values.parseJob.extraVolumeMounts" . }}
```

### Operator and Lurcher Hints
The following code shows an example how the missing configuration option should look like for the operator and lurcher:

```yaml
# example Lurcher configuration values
lurcher:
  # lurcher.env -- Optional environment variables mapped into the lurcher (see: https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/)
  env: []
  # lurcher.envFrom -- Optional mount environment variables from configMaps or secrets (see: https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/#configure-all-key-value-pairs-in-a-secret-as-container-environment-variables)
  envFrom: []
  # lurcher.extraVolumes -- Optional Volumes mapped into the lurcher (see: https://kubernetes.io/docs/concepts/storage/volumes/)
  extraVolumes:
    - name: ca-workdir
      emptyDir: {}
  # lurcher.extraVolumeMounts -- Optional VolumeMounts mapped into the lurcher (see: https://kubernetes.io/docs/concepts/storage/volumes/)
  extraVolumeMounts:
    - mountPath: /etc/ssl/
      name: ca-workdir

# example Operator configuration values
# env -- Optional environment variables mapped into the operator (see: https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/)
env: []
# envFrom -- Optional mount environment variables from configMaps or secrets (see: https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/#configure-all-key-value-pairs-in-a-secret-as-container-environment-variables)
envFrom: []
# volumes -- Optional Volumes mapped into the operator (see: https://kubernetes.io/docs/concepts/storage/volumes/)
volumes:
  - name: ca-workdir
    emptyDir: {}
# volumeMounts -- Optional VolumeMounts mapped into the operator (see: https://kubernetes.io/docs/concepts/storage/volumes/)
volumeMounts:
  - mountPath: /etc/ssl/
    name: ca-workdir
```

**Describe alternatives you've considered**

none

**Additional context**
