### ISSUE TITLE
🐞 Heavy DefectDojo Finding Uploads fail due to Timeout 

### ISSUE THREAD

**Issue by rseedorff** [secureCodeBox/secureCodeBox#331]
**Describe the bug**

As a secureCodeBox user i tried to test the secureCodeBox with the vulnerable BodgetIT WebApp in combination with the Trivy scanner and the new DefectDojo Integration. 

```yaml
apiVersion: "execution.securecodebox.io/v1"
kind: ScheduledScan
metadata:
  name: "trivy-bodgeit"
  namespace: demo-scans
  annotations:
    defectdojo.securecodebox.io/product-type-name: "Demo"
    defectdojo.securecodebox.io/product-name: "BodgeIT"
    defectdojo.securecodebox.io/product-description: |
      The BodgeIt Store is a vulnerable web application which is currently aimed at people who are new to pen testing.
    defectdojo.securecodebox.io/product-tags: vulnerable,appsec,bodgeit,vulnapp
    defectdojo.securecodebox.io/engagement-name: "demo-scans|bodgeit"
    defectdojo.securecodebox.io/engagement-version: "v1.4.0"
    defectdojo.securecodebox.io/engagement-tags: "automated,daily"
spec:
  interval: 24h
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  scanSpec:
    scanType: "trivy"
    parameters:
      - "securecodebox/bodgeit:latest"
```

The BodgeIT docker image is old and that's why trivy identifies about 300 Issues. Uploading all this trivy issues to DefectDojo results regulary in timeout issues like the following one:

```bash
2021-03-19 17:22:23 DEBUG RestTemplate:147 - Writing [{lead=[1], scan_date=[2021-03-19], scan_type=[Trivy Scan], close_old_findings=[true], skip_duplicates=[false], test_type=[165], test=[437], file=[Byte array resource [resource loaded from byte array]]}] as "multipart/form-data"
2021-03-19 17:23:23 DEBUG RestTemplate:147 - Response 504 GATEWAY_TIMEOUT
Exception in thread "main" org.springframework.web.client.HttpServerErrorException$GatewayTimeout: 504 Gateway Time-out: [<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.17.10</center>
</body>
</html>
]
```

**Expected behavior**

Large findings must not result in a timeout issue. Please add a higher appropriate timeout for the upload requests or make them configurable. 

**Additional context**
- DefectDojo Client: https://github.com/secureCodeBox/defectdojo-client-java
- https://stackoverflow.com/questions/55466650/504-gateway-time-out-issue-in-spring-boot-rest-call-for-heavy-recordmore-than-8/55467157
- https://stackoverflow.com/questions/29620828/spring-resttemplate-how-to-set-connect-timeout-and-read-time-out/55794016

**Comment by J12934** [comment]
Mhh this sounds more like a problem with the DefectDojo setup, if this was a "client" timeout it would not get a timeout http response back. But just throw an exception. This looks more like the nginx ingress controller gave up waiting for the DefectDojo service to respond to the request it proxied. You can increase that using annotations on the nginx ingress: https://github.com/kubernetes/ingress-nginx/issues/3976#issuecomment-480777268

**Comment by rseedorff** [comment]
Made my day 🎉 you are right!

After adding the following DefectDojo specific ingress annotation everything works as expected :)

```yaml
    django:
      ingress:
        annotations:
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/proxy-read-timeout: "360"
```
