### ISSUE TITLE
Add matchedRule to cascading scans

### ISSUE THREAD

**Issue by EndPositive** [secureCodeBox/secureCodeBox#493]
### Is your feature request related to a problem?
As a secureCodeBox user, with cascading scans enabled, I would like to know on what CascadingRule a scan has been triggered.

### Current situation
Cascading scans are triggered by checking if a CascadingRule matches one of the findings:

https://github.com/secureCodeBox/secureCodeBox/blob/89570b3e7151858327cd1b6f87a58c68fb734315/hooks/declarative-subsequent-scans/hook.ts#L94-L103

An example CascadingRule:

https://github.com/secureCodeBox/secureCodeBox/blob/89570b3e7151858327cd1b6f87a58c68fb734315/scanners/nmap/cascading-rules/hostscan.yaml#L6-L16

The generated scan only contains `ownerReferences`, but no information on why it was triggered.

### Describe the solution you'd like
We could copy the match onto the cascading scan's metadata:

```yml
apiVersion: "execution.securecodebox.io/v1"
kind: Scan
metadata:
  name: "amass-example.com-nmap-hostscan"
  labels: [...]
  annotations: [...]
  ownerReferences: [...]
  matchedRule:
    category: "Subdomain"
    osi_layer: "NETWORK" 
spec:
  scanType: "nmap"
  parameters:
    # Treat all hosts as online -- skip host discovery
    - "-Pn"
    # Target Port of the finding
    - "example.com"
  cascades: true
```

### Describe alternatives you've considered
We could also move the `metadata.matchedRule` to `spec.matchedRule`. Probably easier to implement with the types.

### Additional context
Should be pretty simple to implement. If you like the format I can create a PR myself. Main or V3 as a base?
