### ISSUE TITLE
Feature: Pre-populate the file system of containers to support SAST scanners

### ISSUE THREAD

**Issue by malexmave** [secureCodeBox/secureCodeBox#707]
## ➹ New Feature implementation request
Pulling out the "pre-populate file system" requirement out of the semgrep issue (#595) so it can be discussed separately, as I would consider this a feature for SecureCodeBox on its own.

### Is your feature request related to a problem?
To recap the discussion from #595: As a semgrep developer, I want to pre-populate the file system of a scanner job so that I can run static analysis scanners on the resulting data. In #595, we are mostly talking about cloning a Git repository to run a SAST scanner on it, but the same feature can also be useful in other contexts, for example, downloading up-to-date word lists for ncrack from the Internet. Thus, this should be a modular setup that can be extended.

### Describe the solution you'd like
After discussions with the team, we propose to use [init containers](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/) internally for this purpose. The syntax proposed in #595 is a good start, however, I would propose a small alteration: make the data sources a list so that multiple downloaders can be chained / combined (i.e., download a git repository for scanning, and another Git repository containing a set of custom semgrep rules that are used by the scanner). So, the proposed syntax would look like this:

```yaml
apiVersion: "execution.securecodebox.io/v1"
kind: Scan
metadata:
  name: "semgrep-juiceshop"
spec:
  scanType: "semgrep"
  parameters:
    - "--config"
    - "p/ci"
    - "/etc/repo"
  prepopulateFilesystemFrom:
    - git:
      mountPoint: /etc/repo
      repo_url: "https://github.com/bkimminich/juice-shop.git"
      secretRef:
        name: https-credentials
    - git:
      mountPoint: /etc/rules
      repo_url: "https://github.com/my-organization/semgrep-rules.git"
      secretRef:
        name: https-credentials
```

(The exact arguments are up for debate and would have to be decided for each downloader separately, it's more of a general layout).

### Describe alternatives you've considered
Extending each SAST scanner with their own functionality to download repositories, rules and other things from the Internet. Would result in redundant code.

### Additional Considerations
We would also need to figure out what downloaders we would want to support. So far, I have come up with the following list:
1. VCS (Git, SVN, ...)
2. HTTP(S) (curl, curl+unzip, curl+untar, ...)
3. ... Your ideas? Possibilities may include S3, and it could also be an alternative way for mounting content from k8s secrets [as in the ncrack scanner documentation](https://docs.securecodebox.io/docs/scanners/ncrack#setup-with-custom-files) if that is desired.

Looking for feedback on this proposal, especially on how the YAML syntax should be structured to be both intuitive and flexible enough to support different authentication schemes for Git etc.
