### ISSUE TITLE
Jobs not starting in Vagrant setup 

### ISSUE THREAD

**Issue by hailstorm1422** [secureCodeBox/secureCodeBox#975]
Hi Team,

I have setup SCB via vagrant from the latest codebase, but when i ssh in to the vagrant box and execute the scans i'm not able to see the job started.

Here is the PoC:
![image](https://user-images.githubusercontent.com/6916721/153560849-21932e57-4660-4db9-a9f3-999e5f9c427c.png)

Steps to reproduce:

1. vagrant up
2. vagrant ssh
3. Create a scan config yaml file

```
vagrant@securecodebox:~$ cat nmap-scan.yaml
apiVersion: "execution.securecodebox.io/v1"
kind: Scan
metadata:
  name: "nmap-scanme.nmap.org"
spec:
  scanType: "nmap"
  parameters:
    - scanme.nmap.org

```

4. kubectl apply -f nmap-scan.yaml
5. kubectl get scans
6. kubectl get jobs

Additionally, i'm facing these following errors while using kubectl on the deployed cluster

![image](https://user-images.githubusercontent.com/6916721/153561283-ae46c3a0-ed2e-41af-84c1-02a3447ef5ce.png)

Best,
@hailstorm1422
